### ISSUE TITLE
Css ở header bị đè thuộc tính với nút Home và News

### ISSUE THREAD

**Issue by Dg0210** [haku1971/AVS#11]
![image](https://user-images.githubusercontent.com/46072991/77339618-a02eda80-6d5e-11ea-803b-dbdb3cce2ade.png)

**Comment by Na2405** [comment]
![image](https://user-images.githubusercontent.com/53162193/77456346-af308e00-6e2d-11ea-8117-66adcdcf2b3c.png)

đã sửa được head để nhưng css ở button trong drop down bị thừa đoạn trống ở bên phải cần xem lại
