### ISSUE TITLE
Không load được new khi không đăng nhập

### ISSUE THREAD

**Issue by Na2405** [haku1971/AVS#4]
Trong trường hợp không đăng nhập thì trang new detail sẽ bị lỗi 500 không reload được

**Comment by Na2405** [comment]
có thể do check thiếu trường hợp khi lấy thông tin để validate cmt hay like thuộc về ai, nên để ý kĩ phần đấy

**Comment by quangnhse05858** [comment]
nguyên nhân là do jsp chưa mới chỉ hiển thị cho người đã đăng nhập,đã cập nhật thêm
