### ISSUE TITLE
Css table của trang admin bị trùng với table của trang visualize

### ISSUE THREAD

**Issue by haku1971** [haku1971/AVS#6]
![image](https://user-images.githubusercontent.com/53165001/77259905-0f50f400-6cb7-11ea-80b3-93bd9d0852a8.png)

**Comment by Na2405** [comment]
đã chỉnh lại css từ "tr" sang ".tabcontent tr"

**Comment by Na2405** [comment]
à đã thay css "tr" thành ".tabcontent tr" và đã fix được lỗi
